# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Specialty
Specialty.destroy_all
Specialty.create(
  [
    { name: 'Abuso de álcool' },
    { name: 'Acompanhamento psicológico' },
    { name: 'Adoção de filhos' },
    { name: 'Adolêscencia' },
    { name: 'Agorafobia' },
    { name: 'Anorexia nervosa' },
    { name: 'Ansiedade' },
    { name: 'Ansiedade Generalizada (TAG)' },
    { name: 'Autismo' },
    { name: 'Autoconhecimento' },
    { name: 'Autoestima' },
    { name: 'Automutilação' },
    { name: 'Avaliação neuropsicológica' },
    { name: 'Borderline' },
    { name: 'Bulimia nervosa' },
    { name: 'Bournout' },
    { name: 'Câncer' },
    { name: 'Casais' },
    { name: 'Cirúrgia bariátrica' },
    { name: 'Ciúmes' },
    { name: 'Coaching executivo' },
    { name: 'Compulsão alimentar' },
    { name: 'Compulsão por compras' },
    { name: 'Compulsões' },
    { name: 'Conflitos amorosos' },
    { name: 'Conflitos familiares' },
    { name: 'Coronavírus' },
    { name: 'Crise existencial' },
    { name: 'Cuidados paliativos' },
    { name: 'Déficit de atenção (TDA/TDAH)' },
    { name: 'Depêndencia química' },
    { name: 'Depressão' },
    { name: 'Depressão pós-parto' },
    { name: 'Desenvolvimento pessoal' },
    { name: 'Dificuldades no casamento' },
    { name: 'Disfunções sexuais' },
    { name: 'Dislexia' },
    { name: 'Distúrbios alimentares' },
    { name: 'Doenças crônicas' },
    { name: 'Dores crônicas' },
    { name: 'Drogas' },
    { name: 'Ejaculação precoce' },
    { name: 'Emagrecimento' },
    { name: 'Endividamento' },
    { name: 'Esquizofrenia' },
    { name: 'Estresse' },
    { name: 'Estresse pós-traumático (TEPT)' },
    { name: 'Família' },
    { name: 'Fobia social' },
    { name: 'Fobias' },
    { name: 'Gagueira' },
    { name: 'Hiperatividade' },
    { name: 'Identidade de genêro' },
    { name: 'Impotência sexual' },
    { name: 'Infância' },
    { name: 'Insegurança' },
    { name: 'Insônia' },
    { name: 'Inteligência emocional' },
    { name: 'Isolamento social' },
    { name: 'LGBTQI+' },
    { name: 'Ludoterapia' },
    { name: 'Luto perinatal' },
    { name: 'Mau humor crônico' },
    { name: 'Medos' },
    { name: 'Menopausa' },
    { name: 'Mindfulness' },
    { name: 'Morte e luto' },
    { name: 'Neuropsicologia' },
    { name: 'Neuropsicologia do idoso' },
    { name: 'Neuropsicologia infantil' },
    { name: 'Obesidade' },
    { name: 'Orientação de pais' },
    { name: 'Orientação para cirurgia bariátrica' },
    { name: 'Orientação profissional' },
    { name: 'Orientação vocacional' },
    { name: 'Parar de fumar' },
    { name: 'Perda de libido/desejo' },
    { name: 'Perda de memória' },
    { name: 'Preparação para aposentadoria' },
    { name: 'Problemas financeiros' },
    { name: 'Produtividade e performance profissional' },
    { name: 'Psicologia infantil' },
    { name: 'Psicologia Intercultural' },
    { name: 'Psicologia Organizacional' },
    { name: 'Puerpério' },
    { name: 'Racismo e questões raciais' },
    { name: 'Relacionamentos abusivos' },
    { name: 'Relacionamentos afetivos' },
    { name: 'Reprodução Assistida' },
    { name: 'Sexualidade' },
    { name: 'Síndrome de asperger' },
    { name: 'Síndrome do pânico' },
    { name: 'Suícidio' },
    { name: 'Supervisão clínica em psicologia' },
    { name: 'Terapia sexual' },
    { name: 'TOC - Transtorno Obsessivo Compulsivo' },
    { name: 'Transição de carreiras' },
    { name: 'Transtorno bipolar' },
    { name: 'Transtorno de Personalidade' },
    { name: 'Tristeza materna' },
    { name: 'Violência doméstica e sexual' }
  ]
)

# Approach
Approach.destroy_all
Approach.create(
  [
    { name: 'Análise Bioenergética' },
    { name: 'Análise do Comportamento | Behaviorismo' },
    { name: 'Análise Transacional' },
    { name: 'Coaching de Carreira' },
    { name: 'Coaching de Emagrecimento' },
    { name: 'Coaching de Negócios' },
    { name: 'Coaching de Vida' },
    { name: 'Coaching Executivo' },
    { name: 'Construcionismo Social' },
    { name: 'Corporal | Reichiana' },
    { name: 'Daseinsanalyse' },
    { name: 'Esquizoanálise' },
    { name: 'Existencialismo Sartreano' },
    { name: 'Fenomenologia Existêncial' },
    { name: 'Gestalt Terapia' },
    { name: 'Hipnoterapia' },
    { name: 'Humanista' },
    { name: 'Humanista | Abordagem centrada na pessoa' },
    { name: 'Logoterapia' },
    { name: 'Ludoterapia' },
    { name: 'Mindfulness' },
    { name: 'Neuropsicológia' },
    { name: 'Programação Neurolinguística - PNL' },
    { name: 'Psicanálise | Bion' },
    { name: 'Psicanálise | Freud' },
    { name: 'Psicanálise | Klein' },
    { name: 'Psicanálise | Lacan' },
    { name: 'Psicanálise | Winnicott' },
    { name: 'Psicodinâmica' },
    { name: 'Psicodrama' },
    { name: 'Psicologia Analítica | Jung' },
    { name: 'Psicologia baseada em Sartre' },
    { name: 'Psicologia Clínica' },
    { name: 'Psicologia do Esporte' },
    { name: 'Psicologia hístorico-cultural' },
    { name: 'Psicologia Organizacional e do Trabalho' },
    { name: 'Psicologia Positiva' },
    { name: 'Psicopedagogia' },
    { name: 'Psicossomática Psicanalítica' },
    { name: 'Psicoterapia Breve' },
    { name: 'Psicoterapia Existencialista'},
    { name: 'Teoria do Apego' },
    { name: 'Terapia Breve Focada na Solução' },
    { name: 'Terapia Cognitiva Comportamental Dialética'},
    { name: 'Terapia Cognitivo Comportamental' },
    { name: 'Terapia do Esquema' },
    { name: 'Terapia EMDR' },
    { name: 'Terapia Familiar' },
    { name: 'Terapia Narrativa' },
    { name: 'Terapia Relacional Sistêmica' },
    { name: 'Transpessoal' }
  ]
)

